doc-warnings: true
test-warnings: true

pylint:
    run: false

pep8:
    full: true

pyflakes:
    run: false

mccabe:
    run: false

dodgy:
    run: false

pep257:
    run: false

profile-validator:
    run: false
