#py-cd-talk.gocd.yaml
environments:
  dev:
    pipelines:
      - flags_quick
      - flags_full
pipelines:
  flags_quick:
    group: flags
    locking: off
    materials:
      flags_source:
        git: https://github.com/bolsote/py-cd-talk.git
    stages:
      - Linting: 
        jobs:
          Linting:
            tasks:
              - exec:
                run_if: passed
                command: tox
                arguments:
                  - "-e linting"
          Security:
            tasks:
              - exec:
                run_if: passed
                command: tox
                arguments:
                  - "-e security"
      - unit:
        jobs:
          tests_pypy3:
            environment_variables:
              COVERAGE_FILE: .coverage.unit.pypy3
            artifacts:
              - test:
                source: report.xml
              - build:
                source: .coverage.unit.pypy3
                destination: coveragedata/
            tasks:
              - exec:
                run_if: passed
                command: tox
                arguments:
                  - "-e pypy3-cov"
                  - "--"
                  - "-m unit"
                  - "--junitxml=report.xml"
          tests_py36:
            environment_variables:
              COVERAGE_FILE: .coverage.unit.py36
            artifacts:
              - test:
                source: report.xml
              - build:
                source: .coverage.unit.py36
                destination: coveragedata/
            tasks:
              - exec:
                run_if: passed
                command: tox
                arguments:
                  - "-e py36-cov"
                  - "--"
                  - "-m unit"
                  - "--junitxml=report.xml"
  flags_full:
    group: flags
    locking: off
    materials:
      flags_source:
        git: https://github.com/bolsote/py-cd-talk.git
        branch: master
      flags_quick:
        pipeline: flags_quick
        stage: tnit
    stages:
      - integration:
        jobs:
          tests_pypy3:
            environment_variables:
              COVERAGE_FILE: .coverage.integration.pypy3
            artifacts:
              - test:
                source: report.xml
              - build:
                source: .coverage.integration.pypy3
                destination: coverage/
            tasks:
              - exec:
                run_if: passed
                command: tox
                arguments:
                  - "-e pypy3-cov"
                  - "--"
                  - "-m integration"
                  - "--junitxml=report.xml"
          tests_py36:
            environment_variables:
              COVERAGE_FILE: .coverage.integration.py36
            artifacts:
              - test:
                source: report.xml
              - build:
                source: .coverage.integration.py36
                destination: coverage/
            tasks:
              - exec:
                 run_if: passed
                 command: tox
                 arguments:
                   - "-e py36-cov"
                   - "--"
                   - "-m integration"
                   - "--junitxml=report.xml"
      - component:
        jobs:
          tests_pypy3:
            environment_variables:
              COVERAGE_FILE: .coverage.component.pypy3
            artifacts:
              - test:
                source: report.xml
              - build:
                source: .coverage.component.pypy3
                destination: coverage/
            tasks:
              - exec:
                run_if: passed
                command: tox
                arguments:
                  - "-e pypy3-cov"
                  - "--"
                  - "-m component"
                  - "--junitxml=report.xml"
          tests_py36:
            environment_variables:
              COVERAGE_FILE: .coverage.component.py36
            artifacts:
              - test:
                source: report.xml
              - build:
                source: .coverage.component.py36
                destination: coverage/
            tasks:
              - exec:
                run_if: passed
                command: tox
                arguments:
                  - "-e py36-cov"
                  - "--"
                  - "-m integration"
                  - "--junitxml=report.xml"
      - acceptance:
        jobs:
          tests_pypy3:
            tasks:
              - exec:
                run_if: passed
                command: tox
                arguments:
                  - "-e pypy3-specs"
          tests_py36:
            tasks:
              - exec:
                run_if: passed
                command: tox
                arguments:
                  - "-e py36-specs"
      - coverage:
        jobs:
          coverage_report:
            tabs:
              Coverage: coverage/htmlcov/index.html
            artifacts:
              - test:
                source: htmlcov
                destination: coverage
            tasks:
              - fetch:
                pipeline: flags_quick
                stage: tnit
                job: tests_pypy3
                source: coveragedata/
                run_if: passed
              - fetch:
                pipeline: flags_quick
                stage: unit
                job: tests_py36
                source: coveragedata/
                run_if: passed
              - fetch:
                pipeline: flags_full
                stage: integration
                job: tests_pypy3
                source: coveragedata/
                run_if: passed
              - fetch:
                pipeline: flags_full
                stage: integration
                job: tests_py36
                source: coveragedata/
                run_if: passed
              - fetch:
                pipeline: flags_full
                stage: component
                job: tests_pypy3
                source: coveragedata/
                run_if: passed
              - fetch:
                pipeline: flags_full
                stage: component
                job: tests_py36
                source: coveragedata/
                run_if: passed
              - exec:
                run_if: passed
                command: tox
                arguments:
                  - "-e coverage-view"
                  - "--"
                  - coveragedata/
