environments:
  flags_master:
    pipelines:
      - release_quick
      - release_full
      - release_package
    agents:
      - fbd37ad3-b2fc-4a22-9106-0a76bc7257ad
      - 36e2b7ab-6f76-4da9-935a-49b56d03f48c
      - 8d18d6f8-892e-4c90-9ced-6c340bd18677
pipelines:
  release_quick:
    group: flags_master
    materials:
      source:
        git: http://github.com/bolsote/py-cd-talk.git
        branch: master
    stages:
      - linting:
          jobs:
            linting:
              tasks:
               - exec:
                   command: tox
                   arguments:
                     - "-e linting"
            security:
              tasks:
                - exec:
                   command: tox
                   arguments:
                     - "-e security"
      - unit:
          jobs:
            tests_pypy3:
              environment_variables:
                COVERAGE_FILE: .coverage.unit.pypy3
              artifacts:
                - test:
                    source: report.xml
                - build:
                    source: .coverage.unit.pypy3
                    destination: coveragedata/
              tasks:
                - exec:
                    run_if: passed
                    command: tox
                    arguments:
                      - "-e pypy3-cov"
                      - "--"
                      - "-m unit"
                      - "--junitxml=report.xml"
            tests_py36:
              environment_variables:
                COVERAGE_FILE: .coverage.unit.py36
              artifacts:
                - test:
                    source: report.xml
                - build:
                    source: .coverage.unit.py36
                    destination: coveragedata/
              tasks:
                - exec:
                    run_if: passed
                    command: tox
                    arguments:
                      - "-e py36-cov"
                      - "--"
                      - "-m unit"
                      - "--junitxml=report.xml"
  release_full:
    group: flags_master
    materials:
      source:
        git: http://github.com/bolsote/py-cd-talk.git
        branch: master
      quick_dependency:
        pipeline: release_quick
        stage: unit
    stages:
      - integration:
          jobs:
            tests_pypy3:
              environment_variables:
                COVERAGE_FILE: .coverage.integration.pypy3
              artifacts:
                - test:
                    source: report.xml
                - build:
                    source: .coverage.integration.pypy3
                    destination: coveragedata/
              tasks:
                - exec:
                    run_if: passed
                    command: tox
                    arguments:
                      - "-e pypy3-cov"
                      - "--"
                      - "-m integration"
                      - "--junitxml=report.xml"
            tests_py36:
              environment_variables:
                COVERAGE_FILE: .coverage.integration.py36
              artifacts:
                - test:
                    source: report.xml
                - build:
                    source: .coverage.integration.py36
                    destination: coveragedata/
              tasks:
                - exec:
                    run_if: passed
                    command: tox
                    arguments:
                      - "-e py36-cov"
                      - "--"
                      - "-m integration"
                      - "--junitxml=report.xml"
      - component:
          jobs:
            tests_pypy3:
              environment_variables:
                COVERAGE_FILE: .coverage.component.pypy3
              artifacts:
                - test:
                    source: report.xml
                - build:
                    source: .coverage.component.pypy3
                    destination: coveragedata/
              tasks:
                - exec:
                    run_if: passed
                    command: tox
                    arguments:
                      - "-e pypy3-cov"
                      - "--"
                      - "-m component"
                      - "--junitxml=report.xml"
            tests_py36:
              environment_variables:
                COVERAGE_FILE: .coverage.component.py36
              artifacts:
                - test:
                    source: report.xml
                - build:
                    source: .coverage.component.py36
                    destination: coveragedata/
              tasks:
                - exec:
                    run_if: passed
                    command: tox
                    arguments:
                      - "-e py36-cov"
                      - "--"
                      - "-m component"
                      - "--junitxml=report.xml"
      - acceptance:
          jobs:
            tests_pypy3:
              tasks:
                - exec:
                    run_if: passed
                    command: tox
                    arguments:
                      - "-e pypy3-specs"
            tests_py36:
              tasks:
                - exec:
                    run_if: passed
                    command: tox
                    arguments:
                      - "-e py36-specs"
      - coverage:
          jobs:
            coverage_report:
              tabs:
                coverage: coverage/htmlcov/index.html
              artifacts:
                - test:
                    source: htmlcov
                    destination: coverage
              tasks:
                - fetch:
                    pipeline: release_quick
                    stage: unit
                    job: tests_pypy3
                    source: coveragedata/
                    run_if: passed
                - fetch:
                    pipeline: release_quick
                    stage: unit
                    job: tests_py36
                    source: coveragedata/
                    run_if: passed
                - fetch:
                    pipeline: release_full
                    stage: integration
                    job: tests_pypy3
                    source: coveragedata/
                    run_if: passed
                - fetch:
                    pipeline: release_full
                    stage: integration
                    job: tests_py36
                    source: coveragedata/
                    run_if: passed
                - fetch:
                    pipeline: release_full
                    stage: component
                    job: tests_pypy3
                    source: coveragedata/
                    run_if: passed
                - fetch:
                    pipeline: release_full
                    stage: component
                    job: tests_py36
                    source: coveragedata/
                    run_if: passed
                - exec:
                    run_if: passed
                    command: tox
                    arguments:
                      - "-e coverage-view"
                      - "--"
                      - coveragedata/
  release_package:
    group: flags_master
    materials:
      source:
        git: http://github.com/bolsote/py-cd-talk.git
        branch: master
      full_dependency:
        pipeline: release_full
        stage: coverage
    stages:
      - package:
          jobs:
            package:
              artifacts:
                - build:
                    source: bin/
                    destination: bin/
              tasks:
                - exec:
                    run_if: passed
                    command: tox
                    arguments:
                      - "-e package"

